### ISSUE TITLE
ability to lock the remote rather than constantly connection and disconnection for doing personal work

### ISSUE THREAD

**Issue by HanaDadfar** [nvda-es/NVDARemote#37]
hello
sometimes, someone is controlling our computer to do some things, but we happen to do some personal work in between in our computer, that we don't wish the person who is controlling our computer to see what we are doing. For example, enterring our personal account information for a website, Looking at and answering important personal messages, looking at the document txt file that we have all our passwords in, etc.
in this cace, we have to disconnect the remote first, do whatever we wantt, then reconnect the remote. We can ask that person to mute the remote, but we can't trust if that person have actually muted the remote, or just told you (I muted) to see what you are doing.
i have 2 suggestions for this.
1: when the controler mutes or unmutes the remote, the computer being controled should get a speech like, (remote muted) and (remote unmuted).
2: the computer being controled should have an option in the remote menu, called lock remote/unlock remote. When set as locked, the controler shouldn't be able to controle the remote computer, shouldn't get any kind of speech or data from the remote computer just as like the remote is disconnected, until the computer being controled toggles the lock remote option. Then, everything would be come back to normal.
what do you think?
thanks

**Comment by amirmahdifard** [comment]
can i take this?
which one do you want me to implement?

**Comment by jmdaweb** [comment]
Before coding, let's study pros and cons, and let's go to the root causes of the problem.
A "lock remote" option should block not only speech, but also keyboard presses of the controller machine. Otherwise, the controller would be able to unlock the session again with a few calculated keyboard presses.
In the other hand, a controller may accidentally lock the remote session on an unattended computer, which is similar to disconnecting, but may be worse for servers since a connection remains active.
Now, let's dive into the real problem: a feature should be provided to connect in controlled mode to the last used session without entering server and password, maybe with a single gesture. This requires saving the last used password in a file or in memory, and has serious security concerns. I will think about the best way of implementing this idea.

**Comment by amirmahdifard** [comment]
@jmdaweb we can prevent the controler to lock the controled computer mistakenly by adding a warning dialog when locking, Like this: Display an alert before the controlled computer disconnects  check box  checked. What do you think? also, can you please answer my other issue? thanks.

**Comment by dragonwolfsp** [comment]
You can store the hash of the password rather than the password itself. This way you can compare the hash of what the user types as the password and the saved hash. In this way you avoid the security concerns related to storing the password since you cant easily dehash a password. Also I am confused as to how this is related to the issue at hand, which involves locking a machine, not saving a connection. I think that @amirmahdifard suggestion of using a similar check to the accidental disconnection of the remote computer would work for this.

**Comment by HanaDadfar** [comment]
@amirmahdifard it looks you wanted to implement this. the thing that i want and makes me satisfyed and enough for me, I only want that when the controler muted or unmuted my computer, i get alerted that they muted me or unmuted me. This is enough for me. If it is possible for  you to implement this, otherwise i'll close this issue.
Thanks

**Comment by amirmahdifard** [comment]
yes I can implement, but sorry, I can't do something with out rights, as I have to code and open pull request, and then if the main developers disagree with my pull request, they will close my pull request, which means I have waysted my time coded something that was regected. Actually once this happned to me. So, i'm sorry, I can't help you hear.

**Comment by HanaDadfar** [comment]
@amirmahdifard thanks.
then I disagreed with the idea provided by @jmdaweb about saving the password, because i don't want to disconnect the setion at all, so saving and hashing the passwords and all those stuf are useless to this suggestion I requested hear.
so, closed this issue as not planned.
