### ISSUE TITLE
Feature request: Checkbox to disable the message of the day

### ISSUE THREAD

**Issue by XLTechie** [nvda-es/NVDARemote#39]
Hello

I use TeleNVDA pretty regularly. It often pops up a Spanish message of the day when it starts, which I can't read. I normally just hit OK, and move on.

 However, today I was trying to create an NVDA portable, that would connect automatically to a server on startup.
The purpose of the portable was to be be pushed over a Remote Incident Manager connection, to give greater accessibility than RIM provides, to a sighted user's remote systems (which I had three to manage).

However, every time I launched the portable with the options configured to connect automatically, the Spanish MOTD would appear, and require interaction before connecting.

After I could not find an option to disable this, I had to go back to using NVDA Remote.

I would like a feature that would allow such messages to be suppressed on startup. Alternatively, I propose that if the "connect automatically" checkbox is selected, any messages be delayed until after the connection is successful.

**Comment by jmdaweb** [comment]
Hi Luke,
The spanish message pops up because you are connecting to the spanish community server, hosted on remote.nvda.es and configured as default server. You may use another relay, such as nvdaremote.com or [your own server](https://github.com/jmdaweb/NVDARemoteServer).
The message we show is similar to a cookie banner on many web sites: it talks about data collection (in short, no data is collected), server logging and includes the URL to our privacy policy. No interaction with the message is required. You can press OK, or just ignore the window and control the remote machine.
However, I will consider implementing this feature request, since many users say that the message is quite anoying. Instead of completely disabling these messages, a checkbox may be added to show them once, regardless of the server configuration.
Regards.

**Comment by XLTechie** [comment]
Thanks @jmdaweb.

Interesting that you say the dialog does not have to be interacted with. I do not recall the "connection established" beep playing until after hitting OK. 
Perhaps I am wrong, but that was my impression at the time.

If cookie consent messages are the model here, I will point out that those do not usually show up again once they are accepted.
